### ISSUE TITLE
Upload to Zenodo

### ISSUE THREAD

**Issue by marijana777** [PYPIT/COS_REDUX#9]
@profxj could we upload the COS_REDUX repository to Zenodo, so we could cite the DOI associated with it? 
The Zenodo support wrote to me: "I believe you should contact the owner of the repository, either by creating an issue in the repo or via email."
Thank you.

**Comment by profxj** [comment]
I fear I just tried but can't get Zenodo to find this Repo.

@marijana777 -- I suggest you:

1. Fork this code into your own account
2. Use Zenodo from there
